name: Overwrite Backstage Latest
on:
  schedule:
  # daily 4:05am
  - cron: '*/5 * * * *'
permissions:
  contents: write
jobs:
  overwrite:
    runs-on: ubuntu-latest
    steps:

      # dont overwrite repo on forks and clones
      - name: Confirm overwrite
        if: ${{ vars.OVERWRITE_WITH_BACKSTAGE_LATEST != 'true' }}
        run: |
          echo "Warning: This action will overwrite the repo with the latest Backstage version.
          You probably don't want this and should delete this file: .github/workflows/overwrite-backstage-latest.yaml"
          exit 1

      # checkout repo
      - uses: actions/checkout@v4
      
      # delete everything except git and heroku files
      - name: Clean
        run: >
          mv backstage.json backstage.old.json


          find . -mindepth 1 -maxdepth 1 
          ! -name '.git' 
          ! -name '.github' 
          ! -name 'app.json' 
          ! -name 'Procfile'
          ! -name 'backstage.old.json'
          ! -name 'heroku.png'
          | xargs rm -rf
      
      # create new backstage app using cli
      - name: Create new app
        run: |
          export BACKSTAGE_APP_NAME=backstage
          npx @backstage/create-app --skip-install

          # copy new backstage app files to root
          # copy . files too
          shopt -s dotglob
          cp -r backstage/* ./
          rm -r backstage

      
      # heroku customizations
      - name: Apply heroku tweaks
        run: |
          sudo snap install yq
          
          # add build commd and cache config to package.json
          jq '.scripts.build = "yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml"' package.json > tmp.json && mv tmp.json package.json
          jq '.cacheDirectories = ["node_modules", "packages/app/node_modules", "packages/backend/node_modules"]' package.json > tmp.json && mv tmp.json package.json

          # add heroku postgres and baseUrl config var to app-config.production.yaml
          yq eval '.app.baseUrl = "${BASE_URL}"' -i app-config.production.yaml
          yq eval '.backend.baseUrl = "${BASE_URL}"' -i app-config.production.yaml
          yq eval '.backend.listen = {"port": {"$env": "PORT"}}' -i app-config.production.yaml
          yq eval '.backend.database = {"client": "pg", "pluginDivisionMode": "schema", "ensureExists": false, "ensureSchemaExists": true, "connection": "${DATABASE_URL}" }' -i app-config.production.yaml

          # getting started in README.md
          cat << EOF > README.md
          <img src="https://backstage.io/logo_assets/svg/Icon_Gradient.svg" alt="backstage" width="100"/> &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; <img src="https://github.com/chap/backstage-button/blob/main/heroku.png" alt="backstage" width="100"/>

          # [Backstage](https://backstage.io) on [Heroku](https://heroku.com)

          Use this button to bootstrap a fresh Backstage app on Heroku from [@backstage/create-app](https://www.npmjs.com/package/@backstage/create-app):

          [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/chap/backstage-button)

          After the app is created, the \`BASE_URL\` needs to be configured:

          \`\`\`sh
          \$ heroku domains -a <your-app>
          <your-app-123>.herokuapp.com

          \$ heroku config:set BASE_URL=https://<your-app-123>.herokuapp.com -a <your-app>
          \`\`\`

          To make changes, clone this repo and push to your Heroku app:

          \`\`\`sh
          \$ git clone https://github.com/chap/backstage-button.git <your-app>/
          \$ cd <your-app>/
          \$ heroku remote:add -a <your-app>
          \$ git push heroku main
          \`\`\`

          You should also push to a canonical git repo:
          \`\`\`sh
          \$ git remote set-url origin https://github.com/<your-app>.git
          \$ git push origin main
          \`\`\`

          The included GitHub action runs once a day and overwrites the file from the latest Backstage release. You probably don\'t want that:
          \`\`\`sh
          \$ rm .github/workflows/overwrite-backstage-latest.yaml
          \`\`\`
          EOF

      - name: Commit
        run: |
          version=$(cat backstage.json | jq -r '.version')

          # don't commit if not a new version
          if cmp -s "backstage.json" "backstage.old.json"; then
            echo "Version unchanged: $version"

          else
            yarn install
            rm backstage.old.json

            git config --global user.name 'Github Action'
            git config --global user.email 'no-reply@github.com'
            git add .
            git commit -am "update backstage app version: $version"
            git push
          fi
